# This file is to generate a cluster in the AWS-Cloudshell

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: learningks
  region: ap-south-1

nodeGroups:
  - name: learning-ks-nodes
    instanceType: t2.micro
    desiredCapacity: 3
    minSize: 3
    maxSize: 4