apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gp3-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-gp3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-with-gp3
  template:
    metadata:
      labels:
        app: app-with-gp3
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: gp3-pvc

--- 

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp3
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true

