apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /exports      # <-- to this folder the nfs will be co0nnected and this must be in the ~/data/exports 
    server: 13.234.114.24  #<--- Put your VM IP here

