apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2  # This is service provided by the AWS

  ---

  # Instead OF gp2 i u want to use the diffrent name 
  # Then we have to create a StorageClass  & the PVS Will look lie this here 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: <Storage_Class_Name>
  resources:
    requests:
      storage: 5Gi

