apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2  # This is service provided by the AWS
